ci:
  autofix_prs: true
  autoupdate_schedule: quarterly
  autoupdate_branch: development

default_language_version:
  node: 16.15.0

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: .*\.svg
  - id: check-merge-conflict
    exclude: .*\.rst
  - id: check-symlinks
  - id: check-case-conflict
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --no-ensure-ascii]
    exclude: .*\.ipynb
  - id: check-toml
  - id: check-yaml

# validate pyproject.toml
- repo: https://github.com/abravalheri/validate-pyproject
  rev: v0.23
  hooks:
  - id: validate-pyproject

# lint and format python codes by ruff
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.10
  hooks:
  - id: ruff
    args: [--fix]
  - id: ruff-format

# lint cython codes
- repo: https://github.com/MarcoGorelli/cython-lint
  rev: v0.16.6
  hooks:
  - id: cython-lint

# format yaml files
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.14.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

# format markdown files
- repo: https://github.com/hukkin/mdformat
  rev: 0.7.22
  hooks:
  - id: mdformat
    # Optionally add plugins
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black

# format docstrings in python codes
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.5
  hooks:
  - id: docformatter
    additional_dependencies: [tomli]
    args: [--in-place]

# lint docstrings by numpydoc
- repo: https://github.com/numpy/numpydoc
  rev: v1.8.0
  hooks:
  - id: numpydoc-validation

# check misspellings in codes and texts
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    additional_dependencies: [tomli]
    args:
    - --ignore-regex=^\s*"image\/(jpeg|png|gif|bmp|tiff)":\s.*
    - --exclude-file=pixi.lock
